name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name : setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: set variables
        id: set_short_sha
        shell: bash
        run: |
              echo $echo {short_sha=GITHUB_SHA::7} >> $GITHUB_OUTPUT
      - name: run test
        shell: bash
        run: |
                curl --request POST \
                --url https://api.github.com/repos/${{github.repository}}/issues \
                --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                --header 'content-type: application/json' \
                --data '{
                "title": "Automated issue for commit: ${{ steps.set_short_sha.outputs.short_sha }}",
                "body": "This issue was automatically created by the GitHub Action workflow ${{ github.workflow }} . \n\n The commit hash was: _${{ github.run_number }}_."
                  }' \
                --fail  